# Generated by Django 4.2.7 on 2023-12-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('kids', 'kids')], max_length=100)),
                ('product_brand', models.CharField(choices=[('Raymond', 'Raymond'), ('U.S. Polo Assn.', 'U.S. Polo Assn.'), ('Peter England', 'Peter England'), ('Chanel', 'Chanel'), ('Calvin Klein', 'Calvin Klein'), ('Nike', 'Nike')], max_length=100)),
                ('product_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE SIZE', 'FREE SIZE')], max_length=100)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_desc', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
