# Generated by Django 4.2.7 on 2023-12-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_cart_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.PositiveIntegerField(),
        ),
    ]
